2025-06-03 13:40:52 [WARNING] monprojet.middleware: [c6564558] Réponse 404 en 0.061s - Taille: 2326 bytes
2025-06-03 13:41:34 [WARNING] monprojet.middleware: [8068779a] Réponse 403 en 0.043s - Taille: 94 bytes
2025-06-03 13:41:41 [WARNING] monprojet.middleware: [568c44bd] Réponse 403 en 0.045s - Taille: 93 bytes
2025-06-03 13:41:44 [WARNING] monprojet.middleware: [d0ba859e] Réponse 403 en 0.047s - Taille: 88 bytes
2025-06-03 13:53:31 [WARNING] monprojet.middleware: [c29eb471] Réponse 404 en 0.171s - Taille: 2326 bytes
2025-06-03 13:53:37 [WARNING] monprojet.middleware: [7806320f] Réponse 404 en 0.003s - Taille: 2403 bytes
2025-06-03 13:53:45 [WARNING] monprojet.middleware: [70b982ea] Réponse 404 en 0.048s - Taille: 2488 bytes
2025-06-03 13:54:23 [WARNING] monprojet.middleware: [8a636f2e] Réponse 404 en 0.089s - Taille: 2488 bytes
2025-06-03 13:54:49 [WARNING] monprojet.middleware: [ae157fc8] Réponse 404 en 0.077s - Taille: 2488 bytes
2025-06-03 13:55:15 [WARNING] monprojet.middleware: [021a29b9] Réponse 404 en 0.051s - Taille: 2488 bytes
2025-06-03 13:55:43 [WARNING] monprojet.middleware: [a156d401] Réponse 404 en 0.090s - Taille: 2488 bytes
2025-06-03 13:56:16 [WARNING] monprojet.middleware: [62fef02e] Réponse 404 en 0.077s - Taille: 2488 bytes
2025-06-03 13:56:59 [WARNING] monprojet.middleware: [3511ce43] Réponse 404 en 0.187s - Taille: 2488 bytes
2025-06-03 13:57:16 [WARNING] blog.models: Suppression de l'article 'Chat Gpt remplace les devs !' (ID: 20)
2025-06-03 14:02:14 [WARNING] monprojet.middleware: [ce3cd524] Réponse 404 en 0.192s - Taille: 2488 bytes
2025-06-03 14:02:47 [WARNING] monprojet.middleware: [97cdb058] Réponse 404 en 0.087s - Taille: 2488 bytes
2025-06-03 14:03:06 [WARNING] monprojet.middleware: [64bc24a2] Réponse 404 en 0.081s - Taille: 2488 bytes
2025-06-03 14:04:07 [WARNING] monprojet.middleware: [aa33da04] Réponse 404 en 0.081s - Taille: 2488 bytes
2025-06-03 14:04:07 [WARNING] monprojet.middleware: [d26c9ab0] Réponse 404 en 0.078s - Taille: 9083 bytes
2025-06-03 14:04:07 [WARNING] monprojet.middleware: [8bc9e14b] Réponse 404 en 0.084s - Taille: 9041 bytes
2025-06-03 14:04:07 [WARNING] monprojet.middleware: [67cf73c4] Réponse 404 en 0.190s - Taille: 9270 bytes
2025-06-03 14:04:14 [WARNING] monprojet.middleware: [7c32374e] Réponse 404 en 0.085s - Taille: 2488 bytes
2025-06-03 14:05:14 [WARNING] monprojet.middleware: [d2c0f6db] Réponse 404 en 0.085s - Taille: 2488 bytes
2025-06-03 14:07:01 [WARNING] monprojet.middleware: [74e2334c] Réponse 404 en 0.077s - Taille: 2488 bytes
2025-06-03 14:08:44 [WARNING] monprojet.middleware: [c7a3f016] Réponse 404 en 0.082s - Taille: 2488 bytes
2025-06-03 14:08:50 [WARNING] monprojet.middleware: [a6e7acc6] Réponse 404 en 0.079s - Taille: 2488 bytes
2025-06-03 14:08:54 [WARNING] monprojet.middleware: [bbb0e175] Réponse 404 en 0.165s - Taille: 2488 bytes
2025-06-03 14:09:06 [WARNING] monprojet.middleware: [a90ae2df] Réponse 404 en 0.060s - Taille: 2326 bytes
2025-06-03 14:09:14 [WARNING] monprojet.middleware: [55f22f13] Réponse 404 en 0.003s - Taille: 2403 bytes
2025-06-03 14:09:18 [WARNING] monprojet.middleware: [f65321ef] Réponse 404 en 0.055s - Taille: 2488 bytes
2025-06-03 14:11:10 [WARNING] monprojet.middleware: [ca7121e8] Réponse 404 en 0.089s - Taille: 2488 bytes
2025-06-03 14:12:49 [WARNING] monprojet.middleware: [31269a3b] Réponse 404 en 0.156s - Taille: 2488 bytes
2025-06-03 14:13:04 [WARNING] monprojet.middleware: [c94b6e61] Réponse 404 en 0.065s - Taille: 2488 bytes
2025-06-03 14:13:13 [WARNING] monprojet.middleware: [d4d7e515] Réponse 404 en 0.186s - Taille: 2488 bytes
2025-06-03 14:13:27 [WARNING] monprojet.middleware: [ce522d04] Réponse 404 en 0.004s - Taille: 2377 bytes
2025-06-03 14:13:43 [WARNING] monprojet.middleware: [96c3db46] Réponse 404 en 0.185s - Taille: 2488 bytes
2025-06-03 14:13:52 [WARNING] monprojet.middleware: [27d6ec96] Réponse 404 en 0.139s - Taille: 2488 bytes
2025-06-03 14:13:58 [WARNING] monprojet.middleware: [459c8bd3] Réponse 404 en 0.081s - Taille: 2488 bytes
2025-06-03 14:14:03 [WARNING] monprojet.middleware: [1c1311d1] Réponse 404 en 0.059s - Taille: 2488 bytes
2025-06-03 14:14:06 [WARNING] monprojet.middleware: [8b698538] Réponse 404 en 0.169s - Taille: 2488 bytes
2025-06-03 14:14:08 [WARNING] monprojet.middleware: [30ad464b] Réponse 404 en 0.059s - Taille: 2488 bytes
2025-06-03 14:14:10 [WARNING] monprojet.middleware: [ae8fd394] Réponse 404 en 0.058s - Taille: 2488 bytes
2025-06-03 14:14:17 [WARNING] monprojet.middleware: [a96948bb] Réponse 404 en 0.077s - Taille: 2488 bytes
2025-06-03 14:14:30 [WARNING] monprojet.middleware: [1e7c7048] Réponse 404 en 0.060s - Taille: 2488 bytes
2025-06-03 14:16:46 [WARNING] monprojet.middleware: [c004ce43] Réponse 404 en 0.002s - Taille: 2403 bytes
2025-06-03 14:16:54 [WARNING] monprojet.middleware: [e118b108] Réponse 404 en 0.167s - Taille: 2488 bytes
2025-06-03 14:17:25 [WARNING] monprojet.middleware: [4fcb150c] Réponse 404 en 0.073s - Taille: 2488 bytes
2025-06-03 14:20:04 [ERROR] monprojet.middleware: [fd4923bd] Exception non gérée: Http404: Directory indexes are not allowed here.
Traceback (most recent call last):
  File "C:\Users\jbert\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jbert\AppData\Roaming\Python\Python312\site-packages\django\views\static.py", line 49, in serve
    raise Http404(_("Directory indexes are not allowed here."))
django.http.response.Http404: Directory indexes are not allowed here.
2025-06-03 14:20:04 [WARNING] monprojet.middleware: [fd4923bd] Réponse 404 en 0.021s - Taille: 2569 bytes
2025-06-03 14:20:07 [WARNING] monprojet.middleware: [7314470c] Réponse 404 en 0.003s - Taille: 2403 bytes
2025-06-03 14:21:32 [WARNING] monprojet.middleware: [f00c0592] Réponse 404 en 0.007s - Taille: 2457 bytes
2025-06-03 14:21:35 [WARNING] monprojet.middleware: [af55b677] Réponse 404 en 0.181s - Taille: 2380 bytes
2025-06-03 14:23:51 [WARNING] monprojet.middleware: [611bf7eb] Réponse 404 en 0.065s - Taille: 2488 bytes
2025-06-03 14:24:34 [WARNING] monprojet.middleware: [7ec4640d] Réponse 404 en 0.083s - Taille: 2488 bytes
2025-06-03 14:26:02 [WARNING] monprojet.middleware: [49cd7239] Réponse 404 en 0.164s - Taille: 2362 bytes
2025-06-03 14:26:19 [WARNING] monprojet.middleware: [29c09316] Réponse 403 en 0.183s - Taille: 2526 bytes
2025-06-03 14:27:23 [WARNING] monprojet.middleware: [457b7d1d] Réponse 403 en 0.163s - Taille: 78 bytes
2025-06-03 14:27:29 [WARNING] monprojet.middleware: [fb8e87b6] Réponse 403 en 0.045s - Taille: 78 bytes
2025-06-03 14:27:33 [WARNING] monprojet.middleware: [da5c3c8e] Réponse 403 en 0.044s - Taille: 2526 bytes
2025-06-03 14:28:01 [WARNING] monprojet.middleware: [c8294c0b] Réponse 404 en 0.004s - Taille: 2475 bytes
2025-06-03 14:28:05 [WARNING] monprojet.middleware: [2958b757] Réponse 404 en 0.004s - Taille: 2403 bytes
2025-06-03 14:33:48 [WARNING] monprojet.middleware: [c4c90c5f] Réponse 404 en 0.004s - Taille: 2475 bytes
2025-06-03 14:33:51 [WARNING] monprojet.middleware: [22f80767] Réponse 404 en 0.003s - Taille: 2403 bytes
2025-06-03 14:34:41 [WARNING] monprojet.middleware: [3e13cd17] Réponse 404 en 0.007s - Taille: 2394 bytes
2025-06-03 14:34:41 [WARNING] monprojet.middleware: [e989d687] Réponse 404 en 0.003s - Taille: 2322 bytes
2025-06-03 14:35:56 [ERROR] monprojet.middleware: [b17cb74c] Exception non gérée: Http404: Directory indexes are not allowed here.
Traceback (most recent call last):
  File "C:\Users\jbert\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jbert\AppData\Roaming\Python\Python312\site-packages\django\views\static.py", line 49, in serve
    raise Http404(_("Directory indexes are not allowed here."))
django.http.response.Http404: Directory indexes are not allowed here.
2025-06-03 14:35:56 [WARNING] monprojet.middleware: [b17cb74c] Réponse 404 en 0.005s - Taille: 2646 bytes
2025-06-03 14:36:00 [ERROR] monprojet.middleware: [27ac470c] Exception non gérée: Http404: Il n’est pas autorisé d’afficher le contenu de ce répertoire.
Traceback (most recent call last):
  File "C:\Users\jbert\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jbert\AppData\Roaming\Python\Python312\site-packages\django\views\static.py", line 49, in serve
    raise Http404(_("Directory indexes are not allowed here."))
django.http.response.Http404: Il n’est pas autorisé d’afficher le contenu de ce répertoire.
2025-06-03 14:36:00 [WARNING] monprojet.middleware: [27ac470c] Réponse 404 en 0.078s - Taille: 2597 bytes
2025-06-03 14:36:52 [WARNING] monprojet.middleware: [b0397a06] Réponse 404 en 0.054s - Taille: 2488 bytes
2025-06-03 14:37:18 [WARNING] monprojet.middleware: [1bbfa2d0] Réponse 404 en 0.171s - Taille: 2488 bytes
2025-06-03 14:40:01 [WARNING] monprojet.middleware: [5b6b1b41] Réponse 404 en 0.079s - Taille: 2488 bytes
2025-06-03 14:40:28 [WARNING] monprojet.middleware: [e122b9e7] Réponse 404 en 0.095s - Taille: 2488 bytes
2025-06-03 14:40:41 [WARNING] monprojet.middleware: [8830a00a] Réponse 404 en 0.102s - Taille: 2488 bytes
2025-06-03 14:43:58 [WARNING] monprojet.middleware: [f0b7192b] Réponse 403 en 0.048s - Taille: 75 bytes
2025-06-03 14:50:56 [WARNING] monprojet.middleware: [95eda072] Réponse 404 en 0.060s - Taille: 2326 bytes
2025-06-03 15:01:35 [WARNING] monprojet.middleware: [523056f6] Réponse 404 en 0.056s - Taille: 2488 bytes
2025-06-03 15:02:35 [WARNING] blog.models: Suppression de l'article 'Article de test' (ID: 1)
2025-06-03 15:02:57 [WARNING] monprojet.middleware: [642abc46] Réponse 404 en 0.003s - Taille: 2403 bytes
2025-06-03 15:06:38 [WARNING] monprojet.middleware: [184c0d50] Réponse 404 en 0.028s - Taille: 2454 bytes
2025-06-03 15:06:40 [WARNING] monprojet.middleware: [9329e2e5] Réponse 404 en 0.063s - Taille: 2377 bytes
2025-06-03 15:06:42 [WARNING] monprojet.middleware: [33546bba] Réponse 404 en 0.057s - Taille: 2369 bytes
2025-06-03 15:06:42 [WARNING] monprojet.middleware: [41e84cac] Réponse 405 en 0.056s - Taille: 0 bytes
2025-06-03 15:06:45 [WARNING] monprojet.middleware: [6383f4cc] Réponse 404 en 0.060s - Taille: 2369 bytes
2025-06-03 15:06:45 [WARNING] monprojet.middleware: [19f28be4] Réponse 405 en 0.156s - Taille: 0 bytes
2025-06-03 15:08:52 [WARNING] monprojet.middleware: [1df71aa9] Réponse 404 en 0.051s - Taille: 2488 bytes
2025-06-03 15:12:41 [WARNING] monprojet.middleware: [53045aef] Réponse 404 en 0.050s - Taille: 2488 bytes
2025-06-03 15:13:27 [WARNING] monprojet.middleware: [149f3f66] Réponse 404 en 0.076s - Taille: 2488 bytes
2025-06-03 15:24:08 [WARNING] monprojet.middleware: [dc37c7c8] Réponse 403 en 0.053s - Taille: 78 bytes
2025-06-03 15:52:56 [WARNING] monprojet.middleware: [65b0dbc0] Réponse 404 en 0.162s - Taille: 2326 bytes
2025-06-03 15:53:23 [WARNING] blog.models: Suppression de l'article 'Article de test 3' (ID: 27)
2025-06-03 15:53:27 [WARNING] blog.models: Suppression de l'article 'Article de test 2' (ID: 26)
2025-06-03 15:53:31 [WARNING] blog.models: Suppression de l'article 'Article de test 1' (ID: 25)
2025-06-03 14:50:34 [WARNING] monprojet.middleware: [1e073cb6] Réponse 404 en 0.016s - Taille: 2262 bytes
2025-06-03 14:51:37 [WARNING] monprojet.middleware: [b15fae8d] Réponse 404 en 0.011s - Taille: 2209 bytes
2025-06-03 14:51:37 [WARNING] monprojet.middleware: [0968528b] Réponse 404 en 0.007s - Taille: 2347 bytes
2025-06-03 14:51:37 [WARNING] monprojet.middleware: [0c91237c] Réponse 404 en 0.009s - Taille: 2278 bytes
2025-06-03 14:51:37 [WARNING] monprojet.middleware: [27399825] Réponse 404 en 0.006s - Taille: 2281 bytes
2025-06-03 14:51:37 [WARNING] monprojet.middleware: [9c922f64] Réponse 404 en 0.014s - Taille: 2287 bytes
2025-06-03 14:51:37 [WARNING] monprojet.middleware: [4b2ff64d] Réponse 404 en 0.009s - Taille: 2287 bytes
2025-06-03 14:51:37 [WARNING] monprojet.middleware: [a6c89677] Réponse 404 en 0.011s - Taille: 2278 bytes
2025-06-03 14:51:38 [WARNING] monprojet.middleware: [69d56e85] Réponse 404 en 0.012s - Taille: 2236 bytes
2025-06-03 14:52:39 [WARNING] monprojet.middleware: [846cefb6] Réponse 404 en 0.005s - Taille: 2278 bytes
2025-06-03 14:52:39 [WARNING] monprojet.middleware: [ce5502ff] Réponse 404 en 0.010s - Taille: 2287 bytes
2025-06-03 14:52:39 [WARNING] monprojet.middleware: [538f2e6f] Réponse 404 en 0.009s - Taille: 2281 bytes
2025-06-03 14:52:39 [WARNING] monprojet.middleware: [ca10c8e5] Réponse 404 en 0.009s - Taille: 2278 bytes
2025-06-03 14:52:44 [WARNING] monprojet.middleware: [fdcd446e] Réponse 404 en 0.008s - Taille: 2287 bytes
2025-06-03 14:52:44 [WARNING] monprojet.middleware: [8f2b44d9] Réponse 404 en 0.008s - Taille: 2281 bytes
2025-06-03 14:52:44 [WARNING] monprojet.middleware: [9404ad56] Réponse 404 en 0.008s - Taille: 2278 bytes
2025-06-03 14:55:25 [WARNING] monprojet.middleware: [38a058b6] Réponse 404 en 0.040s - Taille: 2278 bytes
2025-06-03 14:55:25 [WARNING] monprojet.middleware: [f13af2bb] Réponse 404 en 0.034s - Taille: 2287 bytes
2025-06-03 14:55:25 [WARNING] monprojet.middleware: [8b936ec0] Réponse 404 en 0.021s - Taille: 2281 bytes
2025-06-03 14:55:25 [WARNING] monprojet.middleware: [c0838936] Réponse 404 en 0.011s - Taille: 2278 bytes
2025-06-03 14:57:16 [WARNING] blog.models: Suppression de l'article 'Chat Gpt remplace les devs !' (ID: 1)
2025-06-03 15:14:39 [WARNING] monprojet.middleware: [63831424] Réponse 404 en 0.024s - Taille: 2209 bytes
2025-06-04 08:02:36 [WARNING] monprojet.middleware: [6cedfb5e] Réponse 404 en 0.099s - Taille: 2185 bytes
2025-06-04 08:02:37 [WARNING] monprojet.middleware: [63e3c1c7] Réponse 404 en 0.010s - Taille: 2236 bytes
2025-06-04 08:04:30 [WARNING] monprojet.middleware: [914c760e] Réponse 404 en 0.010s - Taille: 2347 bytes
2025-06-04 08:10:51 [WARNING] monprojet.middleware: [a02ef11e] Réponse 404 en 0.014s - Taille: 2347 bytes
2025-06-04 08:16:35 [WARNING] monprojet.middleware: [47abe302] Réponse 404 en 0.026s - Taille: 2347 bytes
2025-06-04 08:32:15 [WARNING] monprojet.middleware: [a2e596ff] Réponse 404 en 0.015s - Taille: 2347 bytes
2025-06-04 08:58:19 [ERROR] blog: Erreur lors du chargement de la page d'accueil: <ExtendsNode: extends 'blog/base.html'> must be the first tag in the template.
2025-06-04 08:58:19 [ERROR] monprojet.middleware: [30686ea8] Exception non gérée: TemplateSyntaxError: <ExtendsNode: extends 'blog/base.html'> must be the first tag in the template.
Traceback (most recent call last):
  File "/app/blog/views.py", line 38, in home
    return render(request, 'blog/home.html', context)
  File "/usr/local/lib/python3.10/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/local/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/local/lib/python3.10/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/usr/local/lib/python3.10/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/usr/local/lib/python3.10/site-packages/django/template/engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "/usr/local/lib/python3.10/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "/usr/local/lib/python3.10/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/usr/local/lib/python3.10/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 514, in parse
    self.extend_nodelist(nodelist, compiled_result, token)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 531, in extend_nodelist
    raise self.error(
django.template.exceptions.TemplateSyntaxError: <ExtendsNode: extends 'blog/base.html'> must be the first tag in the template.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/blog/views.py", line 43, in home
    return render(request, 'blog/home.html', {'articles': [], 'categories': []})
  File "/usr/local/lib/python3.10/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/local/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/local/lib/python3.10/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/usr/local/lib/python3.10/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/usr/local/lib/python3.10/site-packages/django/template/engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "/usr/local/lib/python3.10/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "/usr/local/lib/python3.10/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/usr/local/lib/python3.10/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 514, in parse
    self.extend_nodelist(nodelist, compiled_result, token)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 531, in extend_nodelist
    raise self.error(
django.template.exceptions.TemplateSyntaxError: <ExtendsNode: extends 'blog/base.html'> must be the first tag in the template.
2025-06-04 08:58:19 [ERROR] monprojet.middleware: [30686ea8] Réponse 500 en 0.190s - Taille: 214668 bytes
2025-06-04 08:58:24 [ERROR] blog: Erreur lors du chargement de la page d'accueil: <ExtendsNode: extends 'blog/base.html'> must be the first tag in the template.
2025-06-04 08:58:24 [ERROR] monprojet.middleware: [1e7f3816] Exception non gérée: TemplateSyntaxError: <ExtendsNode: extends 'blog/base.html'> must be the first tag in the template.
Traceback (most recent call last):
  File "/app/blog/views.py", line 38, in home
    return render(request, 'blog/home.html', context)
  File "/usr/local/lib/python3.10/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/local/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/local/lib/python3.10/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/usr/local/lib/python3.10/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/usr/local/lib/python3.10/site-packages/django/template/engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "/usr/local/lib/python3.10/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "/usr/local/lib/python3.10/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/usr/local/lib/python3.10/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 514, in parse
    self.extend_nodelist(nodelist, compiled_result, token)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 531, in extend_nodelist
    raise self.error(
django.template.exceptions.TemplateSyntaxError: <ExtendsNode: extends 'blog/base.html'> must be the first tag in the template.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/blog/views.py", line 43, in home
    return render(request, 'blog/home.html', {'articles': [], 'categories': []})
  File "/usr/local/lib/python3.10/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/local/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/local/lib/python3.10/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/usr/local/lib/python3.10/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/usr/local/lib/python3.10/site-packages/django/template/engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "/usr/local/lib/python3.10/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "/usr/local/lib/python3.10/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/usr/local/lib/python3.10/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 514, in parse
    self.extend_nodelist(nodelist, compiled_result, token)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 531, in extend_nodelist
    raise self.error(
django.template.exceptions.TemplateSyntaxError: <ExtendsNode: extends 'blog/base.html'> must be the first tag in the template.
2025-06-04 08:58:24 [ERROR] monprojet.middleware: [1e7f3816] Réponse 500 en 0.147s - Taille: 214961 bytes
2025-06-04 09:07:53 [ERROR] blog: Erreur lors du chargement de la page d'accueil: Unknown argument for 'trans' tag: '!'. The only options available are 'noop', 'context' "xxx", and 'as VAR'.
2025-06-04 09:07:53 [ERROR] monprojet.middleware: [7254653f] Exception non gérée: TemplateSyntaxError: Unknown argument for 'trans' tag: '!'. The only options available are 'noop', 'context' "xxx", and 'as VAR'.
Traceback (most recent call last):
  File "/app/blog/views.py", line 38, in home
    return render(request, 'blog/home.html', context)
  File "/usr/local/lib/python3.10/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/local/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/local/lib/python3.10/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/usr/local/lib/python3.10/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/usr/local/lib/python3.10/site-packages/django/template/engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "/usr/local/lib/python3.10/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "/usr/local/lib/python3.10/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/usr/local/lib/python3.10/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/usr/local/lib/python3.10/site-packages/django/template/loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/usr/local/lib/python3.10/site-packages/django/template/loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/usr/local/lib/python3.10/site-packages/django/template/defaulttags.py", line 967, in do_if
    nodelist = parser.parse(("endif",))
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/usr/local/lib/python3.10/site-packages/django/templatetags/i18n.py", line 443, in do_translate
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Unknown argument for 'trans' tag: '!'. The only options available are 'noop', 'context' "xxx", and 'as VAR'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/blog/views.py", line 43, in home
    return render(request, 'blog/home.html', {'articles': [], 'categories': []})
  File "/usr/local/lib/python3.10/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/local/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/local/lib/python3.10/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/usr/local/lib/python3.10/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/usr/local/lib/python3.10/site-packages/django/template/engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "/usr/local/lib/python3.10/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "/usr/local/lib/python3.10/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/usr/local/lib/python3.10/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/usr/local/lib/python3.10/site-packages/django/template/loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/usr/local/lib/python3.10/site-packages/django/template/loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/usr/local/lib/python3.10/site-packages/django/template/defaulttags.py", line 967, in do_if
    nodelist = parser.parse(("endif",))
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/usr/local/lib/python3.10/site-packages/django/templatetags/i18n.py", line 443, in do_translate
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Unknown argument for 'trans' tag: '!'. The only options available are 'noop', 'context' "xxx", and 'as VAR'.
2025-06-04 09:07:54 [ERROR] monprojet.middleware: [7254653f] Réponse 500 en 0.409s - Taille: 335033 bytes
2025-06-04 09:11:25 [WARNING] monprojet.middleware: [cfafe235] Réponse 404 en 0.021s - Taille: 2347 bytes
2025-06-04 09:11:30 [WARNING] monprojet.middleware: [348f5dd2] Réponse 404 en 0.021s - Taille: 2347 bytes
2025-06-04 09:11:34 [WARNING] monprojet.middleware: [f3fdf615] Réponse 404 en 0.018s - Taille: 2236 bytes
2025-06-04 09:28:00 [WARNING] monprojet.middleware: [a3ab43dd] Réponse 404 en 0.037s - Taille: 2185 bytes
2025-06-04 09:28:00 [ERROR] blog: Erreur lors du chargement de la page d'accueil: Could not parse the remainder: '==' from 'selected_category=='
2025-06-04 09:28:00 [ERROR] monprojet.middleware: [b6aaf0aa] Exception non gérée: TemplateSyntaxError: Could not parse the remainder: '==' from 'selected_category=='
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/django/template/smartif.py", line 179, in translate_token
    op = OPERATORS[token]
KeyError: 'selected_category=='

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/blog/views.py", line 38, in home
    return render(request, 'blog/home.html', context)
  File "/usr/local/lib/python3.10/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/local/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/local/lib/python3.10/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/usr/local/lib/python3.10/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/usr/local/lib/python3.10/site-packages/django/template/engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "/usr/local/lib/python3.10/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "/usr/local/lib/python3.10/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/usr/local/lib/python3.10/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/usr/local/lib/python3.10/site-packages/django/template/loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/usr/local/lib/python3.10/site-packages/django/template/loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/usr/local/lib/python3.10/site-packages/django/template/defaulttags.py", line 853, in do_for
    nodelist_loop = parser.parse(
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/usr/local/lib/python3.10/site-packages/django/template/defaulttags.py", line 952, in do_if
    condition = TemplateIfParser(parser, bits).parse()
  File "/usr/local/lib/python3.10/site-packages/django/template/defaulttags.py", line 885, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/template/smartif.py", line 170, in __init__
    mapped_tokens.append(self.translate_token(token))
  File "/usr/local/lib/python3.10/site-packages/django/template/smartif.py", line 181, in translate_token
    return self.create_var(token)
  File "/usr/local/lib/python3.10/site-packages/django/template/defaulttags.py", line 888, in create_var
    return TemplateLiteral(self.template_parser.compile_filter(value), value)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 600, in compile_filter
    return FilterExpression(token, self)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 703, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '==' from 'selected_category=='

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/django/template/smartif.py", line 179, in translate_token
    op = OPERATORS[token]
KeyError: 'selected_category=='

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/blog/views.py", line 43, in home
    return render(request, 'blog/home.html', {'articles': [], 'categories': []})
  File "/usr/local/lib/python3.10/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/local/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/local/lib/python3.10/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/usr/local/lib/python3.10/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/usr/local/lib/python3.10/site-packages/django/template/engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "/usr/local/lib/python3.10/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "/usr/local/lib/python3.10/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/usr/local/lib/python3.10/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/usr/local/lib/python3.10/site-packages/django/template/loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/usr/local/lib/python3.10/site-packages/django/template/loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/usr/local/lib/python3.10/site-packages/django/template/defaulttags.py", line 853, in do_for
    nodelist_loop = parser.parse(
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/usr/local/lib/python3.10/site-packages/django/template/defaulttags.py", line 952, in do_if
    condition = TemplateIfParser(parser, bits).parse()
  File "/usr/local/lib/python3.10/site-packages/django/template/defaulttags.py", line 885, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/template/smartif.py", line 170, in __init__
    mapped_tokens.append(self.translate_token(token))
  File "/usr/local/lib/python3.10/site-packages/django/template/smartif.py", line 181, in translate_token
    return self.create_var(token)
  File "/usr/local/lib/python3.10/site-packages/django/template/defaulttags.py", line 888, in create_var
    return TemplateLiteral(self.template_parser.compile_filter(value), value)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 600, in compile_filter
    return FilterExpression(token, self)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 703, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '==' from 'selected_category=='
2025-06-04 09:28:00 [ERROR] monprojet.middleware: [b6aaf0aa] Réponse 500 en 0.206s - Taille: 563157 bytes
2025-06-04 09:30:37 [WARNING] monprojet.middleware: [feeedda2] Réponse 404 en 0.020s - Taille: 2236 bytes
2025-06-04 10:02:59 [ERROR] blog: Erreur lors du chargement de la page d'accueil: Invalid block tag on line 106: 'endif', expected 'endblock'. Did you forget to register or load this tag?
2025-06-04 10:02:59 [ERROR] monprojet.middleware: [9e7b0eb9] Exception non gérée: TemplateSyntaxError: Invalid block tag on line 106: 'endif', expected 'endblock'. Did you forget to register or load this tag?
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 505, in parse
    compile_func = self.tags[command]
KeyError: 'endif'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/blog/views.py", line 56, in home
    return render(request, 'blog/home.html', context)
  File "/usr/local/lib/python3.10/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/local/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/local/lib/python3.10/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/usr/local/lib/python3.10/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/usr/local/lib/python3.10/site-packages/django/template/engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "/usr/local/lib/python3.10/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "/usr/local/lib/python3.10/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/usr/local/lib/python3.10/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/usr/local/lib/python3.10/site-packages/django/template/loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/usr/local/lib/python3.10/site-packages/django/template/loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 558, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 106: 'endif', expected 'endblock'. Did you forget to register or load this tag?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 505, in parse
    compile_func = self.tags[command]
KeyError: 'endif'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/blog/views.py", line 61, in home
    return render(request, 'blog/home.html', {
  File "/usr/local/lib/python3.10/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/local/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/local/lib/python3.10/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/usr/local/lib/python3.10/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/usr/local/lib/python3.10/site-packages/django/template/engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "/usr/local/lib/python3.10/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "/usr/local/lib/python3.10/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/usr/local/lib/python3.10/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/usr/local/lib/python3.10/site-packages/django/template/loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/usr/local/lib/python3.10/site-packages/django/template/loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 558, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 106: 'endif', expected 'endblock'. Did you forget to register or load this tag?
2025-06-04 10:02:59 [ERROR] monprojet.middleware: [9e7b0eb9] Réponse 500 en 0.195s - Taille: 296618 bytes
2025-06-04 10:04:47 [WARNING] monprojet.middleware: [54102d93] Réponse 404 en 0.023s - Taille: 2347 bytes
2025-06-04 10:07:33 [WARNING] monprojet.middleware: [f4f89bfb] Réponse 403 en 0.017s - Taille: 75 bytes
2025-06-04 10:08:16 [WARNING] monprojet.middleware: [115007bd] Réponse 404 en 0.016s - Taille: 2347 bytes
